### ISSUE TITLE
Does not work with docker-compose

### ISSUE THREAD

**Issue by atomaka** [osixia/docker-openldap#14]
This image does not work with the docker-compose tool.  This is easily validated.

[Install docker-compose](https://docs.docker.com/compose/install/):

```
curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

Create a docker-compose.yml file:

```
ldap:
  image: osixia/openldap
```

Start the container with `docker-compose run ldap` and the logs will show that "slapd starting" was reached, but queries cannot be run against the service.

Starting the container with docker with `docker run osixia/openldap` works as expected.

On further investigating, this is because the `FIRST_START_DONE` file is never created.  docker-compose seems to die at your [`sleep 3`](https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/container-start.sh#L244).  I am not sure why this is the case.  However, removing that line and rebuilding the container allows me to use the container as expected with docker-compose.

A pull request was not submitted since I am not sure why the sleep was originally added (ead3be2 offers no explanation).

**Comment by osixia** [comment]
Hello,
sleep 3 was added to let slapd terminate properly after the kill command, and before being restarted by daemon.sh

This is already fixed in the next release (1.0.1) 
https://github.com/osixia/docker-openldap/tree/hotfix-1.0.1

the error come from light-baseimage 0.1.0 that terminate when term signals are throwned. By `kill -INT $SLAPD_PID` in this case. 

I will probably release the fixed version 1.0.1 this friday :)

**Comment by atomaka** [comment]
Thanks for the details @osixia!

**Comment by atomaka** [comment]
@osixia any word on a 1.0.1 release?

**Comment by osixia** [comment]
I just push it,
can you test and let me know if it solved the issue ?

By the way i think it's a good practice to set the image version in the docker-compose.yml file :
ldap:
  image: osixia/openldap:1.0.1 

If environment variables or default behavior change in the next release it will not break your config.

**Comment by atomaka** [comment]
It looks like this fixed the issue.  Thanks, @osixia.

**Comment by yoesoff** [comment]
Hi @osixia , I do know why this won't work with docker-compose, even after I use osixia/openldap:1.0.2.
here is my docker-compose.yml : 
...
openldap:
  image: osixia/openldap:1.0.2
  ports:
    - "389:389"
  environment:
    - LDAP_ORGANISATION=softint
    - LDAP_DOMAIN=softint.com.au
    - LDAP_ADMIN_PASSWORD=password

the problem is it keep stuck/stop at "Pulling repository docker.io/osixia/openldap", here is the detail : 

Pulling openldap (osixia/openldap:1.0.2)...
1.0.2: Pulling from osixia/openldap
f4035ccd552a: Pull complete
09e853d45374: Pull complete
1887be597057: Pull complete
b36790f4fd7c: Pull complete
307c8081e6ee: Pull complete
a69db075c744: Pulling fs layer
caaf8d37abdb: Download complete
52769789ae54: Pulling fs layer
d2be0405195d: Download complete
0c65abd21d4f: Download complete
cfbcb41a5d50: Download complete
9a7f68422403: Pulling fs layer
3627a08de6df: Pulling fs layer
3627a08de6df: Layer already being pulled by another client. Waiting.
9a61b6b1315e: Already exists
Pulling repository docker.io/osixia/openldap

any suggestions for this ?
thank
