### ISSUE TITLE
How to create users in command line?

### ISSUE THREAD

**Issue by pedrofurtado** [osixia/docker-openldap#227]
How do I create an LDAP user, in command line, with `docker` command?

**Comment by bazy1983** [comment]
first off you need to get into the container 
docker exec -it <container name> bash
generate new password if you want to add a user
slappasswd -h {<type of encryption>} then hit enter
it will ask you to enter new password and confirm it
once you get your password, copy it so that you can use it when you create a user record
then you do 
ldapadd -x -D "cn=admin,dc=<domain>,dc=<com> -W
then it will ask for admin password, once you enter that, it will wait for you to enter new record like so
dn: ou=groups,dc=<domain>,dc=<com>
objectclass: organizationalUnit
objectclass: top
ou: users
then hit enter twice to push your entry
for users it will go exactly the some way except you need to add more infomation
dn: uid=<username>,ou=<groupname>,dc=<domain>,dc=<com>
cn: first name lastname
givenname: first name
sn: last name
uid: username
uidnumber: <unique number>
userpassword: <the one you created earlier using slappasswd>
gid: this is important to add of you are creating posixAccount
homedirectory: /home/users/<userid>
loginshell: /bin/sh
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top

PS: you probably need to lay your user DN like so "uid,ou,dc,dc" especially if you are using ldap for user login and authentication

**Comment by lhty24** [comment]
Hi, I did the command below but didn't get prompt for admin password. 
    ldapadd -x -D "cn=admin,dc=,dc= -W
Could you pls advise? thanks

**Comment by pedrofurtado** [comment]
Hey @lhty24 . We here create following these steps (we use here docker-compose):

Example:

```bash
mkdir my-folder
cd my-folder

cat >> user.ldif <<EOL
dn: uid=admin,dc=example,dc=org
uid: admin
cn: admin
sn: 3
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
loginShell: /bin/bash
homeDirectory: /home/admin
uidNumber: 14583102
gidNumber: 14564100
userPassword: admin
mail: admin@lbv.org.br
gecos: admin
EOL

docker container run --name my_ldap_server -v $(pwd):/container/service/slapd/assets/test -p 3089:389 -d osixia/openldap

docker container exec my_ldap_server ldapadd -D "cn=admin,dc=example,dc=org" -w admin -f /container/service/slapd/assets/test/user.ldif
```

**Comment by pedrofurtado** [comment]
I will close the issue because for me it was resolved. But let me know @lhty24 if your doubt was satisfied. If not, we can reopen the issue later :+1: :handshake:
