### ISSUE TITLE
Should SSL certs be copied on load?

### ISSUE THREAD

**Issue by wrouesnel** [osixia/docker-openldap#25]
It's somewhat bad behavior for the container to be chown'ing certificates which are bind mounted into it and doesn't work if read-only binds are used and is worse if the certificates are symlinks (i.e. from Let's Encrypt containers).

It would be better behavior for the container to copy the certificates on boot up and then chown them.

**Comment by davemuench** [comment]
I've run into the same problem using LE certs. I spent a while today considering putting a flag into the container to copy the cert from, but we'd also need the ability to do that copy and reload slapd on a regular basis since those certs will eventually change. I don't know how the maintainer feels about adding cron or something like it to the container, so for now I've just put a script together that runs on the host to copy the certs and reload the ldap docker container. Not a good solution but it'll work for now..

**Comment by osixia** [comment]
Hi,
the latest release makes it possible, can you try to run your container with --copy-service and tell me if it fixes this issue ?

example : 
```
docker run [your options] osixia/openldap:1.1.0 --copy-service
```
