### ISSUE TITLE
Enable Password Hashing on Default

### ISSUE THREAD

**Issue by ataraxus** [osixia/docker-openldap#303]
I'm fairly new to LDAP so maybe its just me, but i fear that this is not an issue for me. 
I'm aware that you guys are not responsible for the default behaviour of openldap, but i guess you could do us all an additional favor if you would enable password hashing on default, like the nice guys here #48 have tought me. 

I was pretty shocked after i learned that passwords stored by keycloak into openldap stay clear text, this is at least from my point of view not tolerable. Sadly this is somehow an issue of keycloak, but they wont change the behaviour anytime soon: 

https://issues.jboss.org/browse/KEYCLOAK-4989

**Comment by quanah** [comment]
I've updated the JBOSS ticket as their conclusions seem invalid.

**Comment by quanah** [comment]
And just to note here -- OpenLDAP always hashes the password by default, if a correct LDAP v3 password modification operation is used by the client.  If the client does a direct replace operation on userPassword, then the client is specifically signalling to the server that the client intends to handle any hashing (or not), etc.  I.e., this is entirely a client bug.

The slapo-ppolicy module does have an option that allows the server to instead "take over" when clients attempt to insert a non-hashed password and force it to be hashed, according to the hashing rules of the openldap server process.

Overall, what is indicated here, then, is that there is one or more clients doing direct modification to the userPassword attribute instead of properly doing an LDAP V3 password modification operation, as defined in RFC https://tools.ietf.org/html/rfc3062

**Comment by quanah** [comment]
Also, if it is not desired to allow clients to bypass the openldap server policy, the slapo-ppolicy overlay has an option to force the server to hash any cleartext passwords that get sent in.
