### ISSUE TITLE
Any reasons to force LDAP_DOMAIN to match LDAB_BASE_DN 

### ISSUE THREAD

**Issue by EugenMayer** [osixia/docker-openldap#380]
Due to https://github.com/osixia/docker-openldap/pull/341/files

```
log-helper error "Error: domain $domain_from_base_dn derived from LDAP_BASE_DN $LDAP_BASE_DN does not match LDAP_DOMAIN $LDAP_DOMAIN"
```
LDAP_DOMAIN must now match LDAP_BASE_DN or the server wont start.

In my case, my 

LDAP_DOMAIN is 'auth.dw.company.com'
LDAB_BASE_DN is `DC=company,DC=com`

And more importantly my admin user is now `cn=admin,dc=company,dc=com`
I also have `cn=readonly,dc=company,dc=com` which is used by basically every integrating service

I'am using this image since the early days.

When i now want to migrate to 1.3.0 i seem to be blocked off since i would need to set `LDAB_BASE_DN` to `DC=auth,DC=dw,DC=company,DC=com` and then, during the startup, `cn=admin,DC=auth,DC=dw,dc=company,dc=com` will be expected, which does not exists ( and the container kills )

Any reason to enforce this or the other way around, what can i do now?

**Comment by obourdon** [comment]
@EugenMayer as I was the one to request this code to be merged I felt that the least I could do is provide some feedback/insights on this.

As far as I can tell there have been many issues where the basic discrepancies between all these env variables could cause avoidable basic errors and therefore I thought this was a good idea to enforce some stronger checks instead of having many issues to be posted and investigated

However, I was pretty much sure that there were some use cases I did not take into account and which might be impacted by such decision. This is why I asked for feedback, posting a[ new issue](https://github.com/osixia/docker-openldap/issues/342) some months back but did not get much feedback since then.

May we we could find a fix which still enforce basic errors but without blocking you. Please advise

**Comment by EugenMayer** [comment]
@obourdon i was not aware of that ticket - sorry.

I'am all for avoiding issues for starters with the image, so what you did here makes sense in the first place.

I would not go so far that i see my setup in any way "superior" in not having them equal - but i must say, i cannot see having them equal being superior either.
I would say it comes down to taste but also simplicity and "what you can expect" with the image as defaults, the latter might be a significant argument to keep that check and enforce it.

I would though, since there are no technical reasons to not allow it / do it, allow an opt-in flag to allow those 2 to differ.

Suggestions for names like

LDAP_DOMAIN_BASE_DN_CAN_DIFFER
LDAP_DOMAIN_ADVANCED_MODE
LDAP_DOMAIN_CUSTOM


I would assume one of those ( or any other to you likings ) if set, allows those 2 to differ ( without any warning ). Of course, the default should be "enforce equality" and we explain the "advanced" parameter in the docs.

What do you think?

**Comment by obourdon** [comment]
@EugenMayer no pb at all, monitoring all issues an comments from all the stuff we use is indeed a very tedious and almost impossible thing.

Digging further into your case I may have found an intermediate, easy and quite satisfying solution. Please see [this link](https://github.com/obourdon/osixia-docker-openldap/tree/fix-v1.3.0)

I have also added a new test to check that your case is now handled properly.

Please let me know if this could work for you

**Comment by obourdon** [comment]
@EugenMayer you can give it a try using obourdon/osixia-openldap:fix-v1.3.0

**Comment by EugenMayer** [comment]
@obourdon works perfectly fine, thank you very much! What would you expect for an official release - what is the current timeline?

**Comment by obourdon** [comment]
I have submitted the [new corresponding PR](https://github.com/osixia/docker-openldap/pull/382). @BertrandGouny could you please integrate this in the next release. Many thanks

**Comment by obourdon** [comment]
@BertrandGouny could you please take some time soon to integrate this or discuss about it ? Many thanks in advance

**Comment by BertrandGouny** [comment]
@obourdon thanks for PR. Going to merge this right away :)

**Comment by obourdon** [comment]
@BertrandGouny thanks for merging this

**Comment by mcsky** [comment]
Hello and thank for your work on this image !

@obourdon  could you provide a working env variable configuration, to avoid the following ? 

 `Error: domain prim.UTILISATEUR derived from LDAP_BASE_DN ou=prim,dc=UTILISATEUR does not match LDAP_DOMAIN example.org` error. 

Thank in advance

**Comment by obourdon** [comment]
@mcsky not sure the order of your base DN items is 'relevant' but in your case:

```
docker run --rm -e LDAP_DOMAIN="UTILISATEUR.prim" -e LDAP_BASE_DN="dc=UTILISATEUR,ou=prim" osixia/openldap
```
works

Basically, LDAP_DOMAIN is only composed of (a subset of) concatenation of items right to the = signs in your LDAP_BASE_DN. Therefore the importance of the order

**Comment by mcsky** [comment]
Thank you, it make me pass this error. I'm now facing [this one](https://github.com/osixia/docker-openldap/issues/307)

**Comment by obourdon** [comment]
@mcsky sorry but your statement is a bit vague. Could you please copy/paste your own traces to one of the existing issue (the one corresponding to your new error) please ?

**Comment by tgruenert** [comment]
+1 to @EugenMayer issue.
we are running into the same problem. it is (as far as i understand) not possible to use replication at the moment.
For replication we would set a common BASE_DN for 2 instances. But these two instances can´t have the same LDAP_HOSTNAME.
Looking forward to an fast v1.4 or an v1.3.1 to keep this nice tool runnable for us ;-).

**Comment by obourdon** [comment]
@tgruenert seems like 1.4.0 is not available from DockerHub, in the meantime could you give 1.4.0-dev a try as it is including the fix I did for @EugenMayer. Thanks

**Comment by kevdogg** [comment]
I've tried 1.4.0-dev, however I'm getting this:

`Error: domain ldap.domain.com derived from LDAP_BASE_DN dc=ldap,dc=domain,dc=com does not match LDAP_DOMAIN openldap2.domain.com`

however if as a test if I set LDAP_DOMAIN to openldap.domain.com (which its still mismatched), the slapd will start.  

Any suggestions?  I'm really really surprised why the LDAP_DOMAIN is being checked again the LDAP_BASE_DN when clearly they don't have to be the same?  How would replication work in this instance since the two LDAP_DOMAIN specifications would have to be equal if assuming the internal database structure were the same?
