### ISSUE TITLE
Bugs affecting setting up LDAP replication

### ISSUE THREAD

**Issue by pcolmer** [osixia/docker-openldap#414]
I'm trying to set up two containers with replication between them. The process is failing in a couple of places.

The first is in this script:

https://github.com/osixia/docker-openldap/blob/2a03b392b019adbf810f11bd64a2fed753d77b9d/image/service/slapd/startup.sh#L259-L261

This doesn't declare `ldaps://` as a protocol which causes problems if `LDAP_REPLICATION_HOSTS` does reference `ldaps://`. That is, though, fairly simple to fix in that script.

A bigger problem - and one I cannot find the answer to - is host names and domain names.

If I set `hostname` to be the fully-qualified name and leave `domainname` unset then `/etc/hosts` get correctly set **but** the environment variable `HOSTNAME` in the container gets changed to just the leafname. This then causes `slapd` to just listen to the leafname and not the fully-qualified domain name. That results in `read_config: no serverID / URL match found. Check slapd -h arguments.`

If I set `hostname` to just be the hostname and set `domainname` to the domain then no change is noticed - `/etc/hosts` is set correctly and `HOSTNAME` is still set to the leafname.

If I follow the comments in `docker-compose.yml` and set `hostname` and `domainname` to the same value then `/etc/hosts` is set incorrectly - the entry is a concatenation of both `hostname` and `domainname` **but** `HOSTNAME` is left alone as the fully qualified name! That results in `daemon: bind(6) failed errno=99 (Cannot assign requested address)`.

I cannot find a way to make sure that `/etc/hosts` is set correctly **and** `HOSTNAME` is left as the fully-qualified domain name.

A potential workaround would be to have `HOSTNAME` truncated to the leafname but then modify the references to `slapd` so that they concatenate the `domainname` value but that doesn't seem to make it into the container's environment variables.

**Comment by pcolmer** [comment]
"ldaps://" is deprecated in favour of STARTTLS so I'm now experimenting with removing all references to `HOSTNAME` where `slapd` is run. Instead, just using `ldap:/// ldapi:///`.

**Comment by guptamp** [comment]
@pcolmer Hi, I'm running into the same issues trying to setup replication.
Did you have any luck getting it to work so far?

**Comment by pcolmer** [comment]
@guptamp Yes, I have. I keep meaning to raise a PR and forgetting :). I'll get it done this morning.

**Comment by pcolmer** [comment]
@guptamp https://github.com/osixia/docker-openldap/pull/420

Fairly small changes. If you want to test them yourself, you can put the two modified scripts into a folder called "patches" and then build a modified container with this `Dockerfile`:

```
FROM osixia/openldap:1.3.0
COPY --chown=openldap:openldap patches/startup.sh /container/service/slapd/
COPY --chown=openldap:openldap patches/process.sh /container/service/slapd/
RUN chmod a+x /container/service/slapd/*.sh
```

**Comment by pcolmer** [comment]
@guptamp Please note the changes to `docker-compose.yml` though - it is very important to configure `hostname` and `domainname` correctly. They must **not** be the same value as per the current recommendations.

**Comment by guptamp** [comment]
@pcolmer I tried your fix, but somehow it's still complaining about the -h parameter for slapd...

`Start OpenLDAP...
Waiting for OpenLDAP to start...
5eac17f7 @(#) $OpenLDAP: slapd  (Jul 30 2019 16:24:19) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5eac17f7 read_config: no serverID / URL match found. Check slapd -h arguments.
5eac17f7 slapd stopped.
5eac17f7 connections_destroy: nothing to destroy.

`
How can i see the exact command line which is used to start it?

**Comment by pcolmer** [comment]
@guptamp 

> How can i see the exact command line which is used to start it?

What I did was add this `echo` statement to `process.sh`:

`echo "/usr/sbin/slapd -h $HOST_PARAM ldapi:/// -u openldap -g openldap -d $LDAP_LOG_LEVEL"`

just before the `exec` line. Also, if you add:

`command: ["--loglevel", "debug"]`

to your `docker-compose.yml` file, you'll get more output from the container.

Hope that helps.

**Comment by guptamp** [comment]
@pcolmer It was helpful, thank you.
I think the issue was that i didn't explicitly set a hostname for the container in docker. so when you query hostname --fqdn in process.sh it returns the random docker id that was generated for container hostname.
I was expecting this to be the drived from the ENV Parameters so it drove me crazy till i finally saw the actual command...
Personally I would find it more logical if you would use $HOSTNAME + $LDAP_DOMAIN here.

**Comment by pcolmer** [comment]
@guptamp 

> Personally I would find it more logical if you would use $HOSTNAME + $LDAP_DOMAIN here.

There is, unfortunately, a drawback to that approach. The LDAP domain does not need to be the same as the domain that the host is sitting in, so that approach would be more restrictive. I accept that there will be plenty of occasions when it is the same, but just as many where it isn't.

Glad you got it working though.

**Comment by guptamp** [comment]
@pcolmer You are of course right, I didn't consider that scenario.
However I just can get the second server to start, seems various reasons, one being that in the startup.sh the docker-openldap-was-started-with-replication gets parsed and there only the hostname is written. So essentially it fails already before going into process.sh.

I think I spend already too much time and either need to find another container or fall back to VM's...
But many thanks for your help!
I hope that soon your changes get merged and maybe I can have another try.

**Comment by guptamp** [comment]
@pcolmer You are of course right, I didn't consider that scenario.
However I just can get the second server to start, seems various reasons, one being that in the startup.sh the docker-openldap-was-started-with-replication gets parsed and there only the hostname is written. So essentially it fails already before going into process.sh.

I think I spend already too much time and either need to find another container or fall back to VM's...
But many thanks for your help!
I hope that soon your changes get merged and maybe I can have another try.

**Comment by obourdon** [comment]
@guptamp I am not sure that going back to VM or find another container (I do not know any other nor found one which does this and is still active) will solve your case.

The great advantage of containers is that you can easily and effortlessly clone the repo and integrate the fix to produce your own version (which I do quite often) and this also avoids to wait for official release. Just suggesting ....

**Comment by guptamp** [comment]
@obourdon @pcolmer You are of course right and after sleeping over it and giving the basic sample a try again i realized something.
I believe the issue might be coming from me not manually updating the /etc/hosts file with the fqdn of BOTH hosts.
I was expecting the containers to resolve the dns through my dns server or am i wrong in thinking that?
The second possible issue is that one of the ldap servers is on a none standard port (1389). I put in the correct URI in the Replication_Hosts, but maybe this needs to be modified somewhere else too?

Would it be acceptable to build the images with a modified hosts file if needed? Kind of feels wrong but if it helps...

**Comment by pcolmer** [comment]
@guptamp are you not using FQDNs that are externally resolvable? In other words, if I tried to resolve the hostnames you are using, would I be able to?

If you are using public FQDNs, you shouldn't need to update the hosts file. The containers will perform DNS queries and resolve them normally. The only reason for `/etc/hosts` to be updated with the name of the server itself is so that OpenLDAP knows what it is binding as.

Why are you using a non-standard port? Is it because you are running both containers on the same host?

> Would it be acceptable to build the images with a modified hosts file if needed? Kind of feels wrong but if it helps...

What you could do, if you really feel that is the correct solution for you, is modify `startup.sh` around line 510 so that you can update the hosts file. **However**, my concern would be how you then figure out the correct IP addresses to put in there.

If you are still stuck, perhaps you could share a bit more info about your network setup.

**Comment by guptamp** [comment]
I got it working!
In conclusion i think i had 2 issues.
1. There seems to be a problem if you specify the port in the URI. Once I managed to free up the port on my NAS so i could use it for LDAP things almost worked.
2. There was still a problem with StartTLS and an error -11 which i tracked down to be related to certificate signing. The following LDIF needs to be added to make it work:

``
dn: cn=config
changetype: modify
replace: olcTLSCipherSuite

olcTLSCipherSuite: SECURE256:SECURE128:-VERS-SSL3.0:-VERS-TLS-ALL:+VERS-TLS1.2:+VERS-TLS1.1
``

Thanks @obourdon & @pcolmer for sticking with me!

**Comment by obourdon** [comment]
@guptamp no pb at all and congrats for keeping up trying and succeeding using the container the way you wanted

**Comment by guptamp** [comment]
Just small update for others...
I used the docker-compose from the example folder.
In there the TLSCipherSuite is explicitly set to "SECURE256:-VERS-SSL3.0" and this is what's causing the failure for TLS. I didn't pay enough attention to the other Env vars in there.

**Comment by fabiandsouza88** [comment]
This thread was really helpful for me, as i was setting replication for the first time for my docker environment. @pcolmer I have modifed my process.sh and startup.sh as mentioned in this thread and I am getting the hostnames correctly ie in /etc/hosts as well environment variable hostname.   Im facing a small problem with replication , Node 1 doesnt add the hostname+ipaddress details of node 2 in /etc/hosts file due to which replication fails. If i manaually add the hostname and ipaddress details of node 2 in node 1 (vice versa needs to be done on node2 as well ie add the hostname and ipaddress of node 1)then replication works perfectly fine . How can i fix this?

Thanks in advance

**Comment by pcolmer** [comment]
@fabiandsouza88 in my environment, I'm using fully-qualified domain names that are resolved via DNS. That is why I didn't need to add node 2's details into node 1's /etc/hosts file.

I don't know if that helps you figure out a solution?

**Comment by dkowis** [comment]
> @guptamp #420
> 
> Fairly small changes. If you want to test them yourself, you can put the two modified scripts into a folder called "patches" and then build a modified container with this `Dockerfile`:
> 
> ```
> FROM osixia/openldap:1.3.0
> COPY --chown=openldap:openldap patches/startup.sh /container/service/slapd/
> COPY --chown=openldap:openldap patches/process.sh /container/service/slapd/
> RUN chmod a+x /container/service/slapd/*.sh
> ```

Thanks for this. I had to use it to get the darn thing to start with replication. I spent *super* long trying to figure this out.

**Comment by yhamcit** [comment]
@pcolmer , thanks for digging into the codes. 

### Issue
I'm facing similar issue which leads to "no serverID / URL match found" error after upgrading image to v1.4.0. The root cause cames with the hostname and FQDN just as your description. 
However, my ldap servers are deployed as containers over kubernetes network, via statefulset manifest file, with multi-master replication enabled. In kubernetes context, each pod that wraps the container are assigned a DNS resolvable FQDN, which is formatted as 'pod-name.service-name.namespace.svc.cluster.local'. As kubernetes restricts pod's hostname to leafname only, I haven't found any way to personalize the FQDN. 
This leads to that 'hostname --fqdn' instruction returns 'ldap-x.my-service.my-namespace.svc.cluster.local'. So I added these domain names to LDAP_REPLICATION_HOSTS. But with no luck, the slapd service had been not initializing. Container persist printing following logs.

> *** Running runit daemon...
*** runit daemon started as PID 212
hostname: Name or service not known
Sep  7 10:48:28 ldap-0 syslog-ng[217]: syslog-ng starting up; version='3.19.1'
hostname: Name or service not known
hostname: Name or service not known
hostname: Name or service not known
> 
> ...
> 
> ...
>
> hostname: Name or service not known
hostname: Name or service not known
hostname: Name or service not known

But when I exec the into one of the containers, all fqdns are resolvable.
```bash
[/ldap]$ kubectl exec -it -n ldap ldap-0 -c openldap bash
root@ldap-0:/# python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>import socket
>>>socket.gethostbyname('ldap-0.my-service.my-namespace.svc.cluster.local')
'0.0.0.0'
>>>socket.gethostbyname('ldap-1.my-service.my-namespace.svc.cluster.local')
'10.0.2.45'
>>>socket.gethostbyname('ldap-2.my-service.my-namespace.svc.cluster.local')
'10.0.0.49'
```

I have no idea, what's going wrong.


### Alternative solution
Since putting fqdn in replication list not working. I'm wondering wether it is possible to let user define the hostname via HOSTNAME variable.

https://github.com/osixia/docker-openldap/blob/7ce084bab1f9016830548558241fdefb60862482/image/service/slapd/process.sh#L12-L16

at line #16 , change 
> `exec /usr/sbin/slapd -h "$HOST_PARAM ldapi:///" -u openldap -g openldap -d "$LDAP_LOG_LEVEL"`bash
to
> `exec /usr/sbin/slapd -h "$HOSTNAME ldapi:///" -u openldap -g openldap -d "$LDAP_LOG_LEVEL"`bash

Since I don't have a docker environment. So please correct me if I'm wrong. 
As result of the PR #420, the HOSTNAME variable, /etc/host, leafname and fqdn have been set correctly. So docker users could use the combination of --hostname and $HOSTNAME to control the slapd listening port, while kubernetes users could set $HOSTNAME to kubernetes format.

**Comment by pcolmer** [comment]
@yhamcit 

Your suggested change to line 16 won't quite work because `HOST_PARAM` (which you are replacing with `HOSTNAME`) is more than just the fully qualified domain name. It is the LDAP protocol and port as well.

You said:

> However, my ldap servers are deployed as containers over kubernetes network, via statefulset manifest file, with multi-master replication enabled. In kubernetes context, each pod that wraps the container are assigned a DNS resolvable FQDN, which is formatted as 'pod-name.service-name.namespace.svc.cluster.local'. As kubernetes restricts pod's hostname to leafname only, I haven't found any way to personalize the FQDN.

The hostname *should* be the leafname only. If you look at the example `docker-compose.yml` file, you'll see that you can set `domainname` to the rest of the server's FQDN, e.g.:

```
domainname: my-service.my-namespace.svc.cluster.local
```

Does that help?

**Comment by yhamcit** [comment]
@pcolmer. Thanks for quick reply. There is a mistake in my previous post. I'm going to correct it soon.

#### This is the original solution:
> exec /usr/sbin/slapd -h "$HOSTNAME ldapi:///" -u openldap -g openldap -d "$LDAP_LOG_LEVEL"bash

#### This is the correct solution:
> HOST_PARAM="ldap://$HOSTNAME:$LDAP_PORT ldaps://$HOSTNAME:$LDAPS_PORT" 
> exec /usr/sbin/slapd -h "$HOST_PARAM ldapi:///" -u openldap -g openldap -d "$LDAP_LOG_LEVEL"bash

#### Regarding to set domainname:
Unfortunately, unlike docker-compose.yaml. Kubernetes does not allow for changing the FQDN. Here is the description from [Kubernetes' doc](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields).

> Pod's hostname and subdomain fields
>
> Currently when a pod is created, its hostname is the Pod's metadata.name value.
>
> The Pod spec has an optional hostname field, which can be used to specify the Pod's hostname. When specified, it takes precedence over the Pod's name to be the hostname of the pod. For example, given a Pod with hostname set to "my-host", the Pod will have its hostname set to "my-host".
> 
> The Pod spec also has an optional subdomain field which can be used to specify its subdomain. For example, a Pod with hostname set to "foo", and subdomain set to "bar", in namespace "my-namespace", will have the fully qualified domain name (FQDN) "foo.bar.my-namespace.svc.cluster-domain.example".

The point of my suggeting:
hostname: from hostname field in docker-compose.yml or set by kubernetes, for example 'my-ldap-0'
FQDN:  either from domainname (docker) or fixed value (kubernetes) , for example: 'my-ldap-0.my-service.my-namespace...'
/etc/hosts:   ip-address    FQDN    HOSTNAME-ALIAS(LEAFNAME)
HOSTNAME environment variable: let user make decision and be used in slapd -h argument, so that user could control what is used to launch slapd service. (This might provide some kind of flexibility)

Would it work?

**Comment by pcolmer** [comment]
@yhamcit I'm getting a bit confused ...

> *** HOSTNAME = ldap-0.my-service.my-namespace
*** POD_NAME = ldap-0

Are *both* of these being set by Kubernetes or are you setting `HOSTNAME`? The reason I ask is because that value for `HOSTNAME` is not just a leafname.

Also, are you trying to use these servers from outside the cluster or within it? In other words, are the clients of your LDAP servers also within the "cluster.local" namespace?

**Comment by yhamcit** [comment]
Both POD_NAME & HOSTNAME are set by myself in accord with kubernetes. Meanwhile, kubernetes will set hostname and hostname fqdn automatically. Here is the hostname command output:

```bash
root@ldap-0:/# hostname
ldap-0
root@ldap-0:/# hostname --fqdn
ldap-0.coredbs.my-service.my-namespace.cluster.local
root@ldap-0:/# echo $HOSTNAME
ldap-0.my-service.my-namespace
root@ldap-0:/# echo $POD_NAME
ldap-0
```
"ldap-0.my-service.my-namespace" is the short name that kubernetes could resolve and could be used by pods to communicate each other. I use this shortened string because in original image v1.4.0, when FQDN is used to lauch "slapd -h", the container prints error:

> hostname: Name or service not known

I can not finger out what's wrong and have no idea to fix it. So I'm trying to find a way to bypass.

In my cluster, ldap and ldap clients stays in different namespace, but, still in same cluster. So they could both find each other via the domainname 'pod-name.service-name.namespace'. When I use

` slapd -h "ldap://ldap-0.my-service.my-namespace:389 ldaps://ldap-0.my-service.my-namespace:636 ldapi:///" ... `

to launch the service, and set REPLICATION-HOST-LIST as: 

> LDAP_REPLICATION_HOSTS:
>   \- ldap://ldap-0.my-service.my-namespace
>   \- ldap://ldap-1.my-service.my-namespace
>   \- ldap://ldap-2.my-service.my-namespace

The ldap pods and replicatin would work.

**Comment by pcolmer** [comment]
> In my cluster, ldap and ldap clients stay in different namespace, but, still in same cluster. So they could both find each other via the domainname 'pod-name.service-name.namespace'.

Can they find each other with "pod-name.service-name.namespace.cluster.local"? I ask that because, earlier, you said "But when I exec the into one of the containers, all fqdns are resolvable."

If you exec into one of the LDAP containers, what does /etc/hosts look like and what is the `slapd` process running with?

**Comment by yhamcit** [comment]
It works for me.

#### Here is the log from ldap server booting:

> *** --- process file : /container/environment/01-custom/env.yaml ---
*** --- process file : /container/environment/98-default/default.yaml ---
*** --- process file : /container/environment/99-default/default.yaml ---
*** ignore : LDAP_LOG_LEVEL = 256 (keep LDAP_LOG_LEVEL = 256 )
*** Run commands before process...
*** ------------ Environment dump ------------
*** PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
*** HOSTNAME = ldap-2.my-service.my-namespace
*** SERVICE_NAME = coredbs
> 
> ...
> 
>*** LDAP_PORT = 389
*** LDAPS_PORT = 636
*** ------------------------------------------
*** Running runit daemon...
*** runit daemon started as PID 614
exec /usr/sbin/slapd -h ldap://ldap-2.my-service.my-namespace:389 ldapi:/// -u openldap -g openldap -d 256
5f5853a8 @(#) $OpenLDAP: slapd 2.4.50+dfsg-1~bpo10+1 (May  4 2020 05:25:06) $
        Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
Sep  9 12:01:44 ldap-2 syslog-ng[620]: syslog-ng starting up; version='3.19.1'
5f5853a8 slapd starting
5f5853a8 slap_client_connect: URI=ldap://ldap-1.my-service.my-namespace
5f5853a8 slap_client_connect: URI=ldap://ldap-1.my-service.my-namespace
>
> 5f5853cb conn=1000 fd=14 ACCEPT from IP=127.0.0.1:58040 (IP=0.0.0.0:389)
5f5853cb conn=1001 fd=16 ACCEPT from IP=127.0.0.1:58042 (IP=0.0.0.0:389)
...
5f5853cc conn=1003 fd=17 TLS established tls_ssf=256 ssf=256
5f5853cc conn=1002 fd=14 TLS established tls_ssf=256 ssf=256
5f5853cc conn=1003 op=1 BIND dn="cn=admin,cn=config" method=128
...
5f5853cc conn=1002 op=1 BIND dn="cn=admin,dc=my-org,dc=org" method=128
...
5f5853cc conn=1003 op=2 SRCH base="cn=config" scope=2 deref=0 filter="(objectClass=*)"
5f5853cc conn=1003 op=2 SRCH attr=* +
5f5853cc conn=1002 op=2 SRCH base="dc=my-org,dc=org" scope=2 deref=0 filter="(objectClass=*)"
5f5853cc conn=1002 op=2 SRCH attr=* +
5f5853cd conn=1001 op=3 UNBIND
5f5853cd conn=1001 fd=16 closed

#### To verify, exec into container:

```bash
root@ldap-0:/# hostname
> ldap-0
root@ldap-0:/# hostname --fqdn
> hostname: Name or service not known
root@ldap-0:/# echo $HOSTNAME
> ldap-0.my-service.my-namespace
root@ldap-0:/# cat /etc/hosts
> 0.0.0.0 ldap-0.my-service.my-namespace.svc.cluster.local ldap-0.my-service.my-namespace
> # Kubernetes-managed hosts file.
> 127.0.0.1       localhost
> ::1     localhost ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> fe00::0 ip6-mcastprefix
> fe00::1 ip6-allnodes
> fe00::2 ip6-allrouters
root@ldap-0:/# python3
> Python 3.7.3 (default, Dec 20 2019, 18:57:59)
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import socket
> >>> socket.gethostbyname('ldap-0.my-service.my-namespace')
> '0.0.0.0'
> >>> socket.gethostbyname('ldap-1.my-service.my-namespace')
> '10.0.0.58'
> >>> socket.gethostbyname('ldap-2.my-service.my-namespace')
> '10.0.2.55'
> >>> quit()
```

It's abnormal that hostname --fqdn command not working. It means FQDN is not set. However, this solution still works...
Since 'ldap-2.my-service.my-namespace' and 'ldap-2.my-service.my-namespace' are dns resolvable from 'ldap-0.my-service.my-namespace', I can do ldapsearch like this from 'ldap-0':

```bash
root@ldap-0:/# ldapsearch -x -H ldap://ldap-2.my-service.my-namespace -b "cn=config" -D "cn=admin,cn=config" -W -Z
> Enter LDAP Password:
> # extended LDIF
> #
> # LDAPv3
> # base <cn=config> with scope subtree
> # filter: (objectclass=*)
> # requesting: ALL
> #
> 
> # config
> dn: cn=config
> objectClass: olcGlobal
> cn: config
> ...
```

**Comment by kevdogg** [comment]
@pcolmer 
Thanks a lot for the info contained in this thread. It really helped me out particularly when setting the domain and hostname.
I'm running osixia 1.40.

The actual replication between two docker images located on two different VMs seems to be working.  I can make changes on the one instance and see the changes on the other.  I'm getting this in the logs of one of the instances:

```
TLS: can't connect: (unknown error code).
5ff0efb2 slap_client_connect: URI=ldap://openldap.openldap-net Error, ldap_start_tls failed (-11)
5ff0efb2 do_syncrepl: rid=101 rc -11 retrying
```

I following parameters were set automatically:
olcTLSCipherSuite: SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC

olcSyncrepl: {0}rid=101 provider=ldap://openldap.openldap-net binddn="cn=admin,dc=ldap,dc=gohilton,dc=com" bindmethod=simple credentials="admin" searchbase="dc=ldap,dc=domain,dc=com" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical
olcSyncrepl: {1}rid=102 provider=ldap://openldap2.openldap.net binddn="cn=admin,dc=ldap,dc=gohilton,dc=com" bindmethod=simple credentials="admin" searchbase="dc=ldap,dc=domain,dc=com" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical

The certificates I'm using are SSL self-signed certificates.  

With the starttls command -- I'm really wondering about something regarding TLS.  I does the one of the replication serverspresent client certs to the other replication server, or does this not occur?  I'm assuming by my error presented above the TLS connection is failing and the transfer is occurring without TLS?

Here are my environmental variables:

```
      LDAP_LOG_LEVEL: 256
      LDAP_ORGANISATION: domain
      LDAP_DOMAIN: openldap.domain.com
      LDAP_BASE_DN: dc=ldap,dc=domain,dc=com
      LDAP_ADMIN_PASSWORD: **PASS*
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: cert.pem
      LDAP_TLS_KEY_FILENAME: key.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_PROTOCOL_MIN: 3.4
      LDAP_TLS_VERIFY_CLIENT: try
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_SSL_HELPER_PREFIX: ldap
      LDAP_OPENLDAP_UID: 439
      LDAP_OPENLDAP_GID: 439
      LDAP_BACKUP_TTL: 15
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://openldap.openldap-net','ldap://openldap2.openldap-net']" 
```

**Comment by pcolmer** [comment]
@kevdogg 

> The certificates I'm using are SSL self-signed certificates.

This is probably the root cause.

SSL certificates work best when there is a trusted Certificate Authority (CA) issuing the certificates. The hassle with self-signed certificates is that there is no such CA because the individual server has signed its own certificate and that server doesn't exist as a CA on the other server(s).

Any system trying to connect to a service that is using self-signed certificates will have a problem with trusting that certificate. In a production environment, your choices are:

1. Set up a private CA and add that CA to the trusted list of CAs on all systems or

2. (Preferably) Use publicly issued certificates such as those from Let's Encrypt (free!)

Once you make that change, the TLS issues should go away, but you may hit other problems as you seem to have several different domains being referenced, although that may just be incomplete redaction on your part.

**Comment by kevdogg** [comment]
@pcolmer 

Thanks for reply.  Yea the self-signed certs may be a problem however Let's Encrypt and other such authorities which I regularly utilize don't offer the ability for client SSL certificates so I'm kind of stuck rolling my own. I've created all the certificates with only local CA and then manually distribute them from that source.  I've verified all the client and server certificates can validate against the CA so I'm pretty sure I've set the certificates up correctly as I'm using similar certificates in other containers.

I don't know how to describe things, but this container is "fragile". I get things up and running and then the container will totally break when trying to add replication.  I've bin mounted the directory containing the ssl certs, but I've noticed that if I change some of the SSL certs in the bin mount, they don't get copied over to the /var/run directory unless the container is rebuilt. I wasn't aware the actual start process worked this way.   I wish I had more errors to post to help debug the problem, however it seems that anytime I make a change with the replication parameters, the entire container "breaks" and the slapd wont start.  I've noticed if I removed the replication parameters from the docker-compose file, the changes do make it back into the container since the flag "started-with-replication" is still present although I've removed these from the docker-compose.  The way things are constructed it appears things are kind of setup as a one way process --- set things up initially and you can add features along the way (such as tls, replication, SSL clientetc), but later its really hard to remove these features.

**Comment by pcolmer** [comment]
@kevdogg 

> set things up initially and you can add features along the way (such as tls, replication, SSL client certs, etc), but later its really hard to remove these features once added

Some of this is likely to be down to how OpenLDAP itself works. The software stores its configuration in itself so trying to remove features does require some careful attribute editing/removal.

> Let's Encrypt and other such authorities which I regularly utilize don't offer the ability for client SSL certificates so I'm kind of stuck rolling my own.

Correct - if you are wanting to do client certificates then you will need your own CA.

You may find it easier to build your own derivative of the OpenLDAP Docker image. See https://github.com/osixia/docker-openldap#advanced-user-guide for an example, including adding certs.

**Comment by kevdogg** [comment]
@pcolmer 

Building a custom container is only going to solve a little bit of the issues.  For example you could add custom certs via a Dockerfile, or add these as a bind mounted volume.  The problem however with the example is that the certs are only copied to the /var/run subdirectory tree upon container creation. Additionally part of screwing around with openldap for me is "I don't really know exactly what I want initially".  I kind of learn by doing which I think is a lot of DevOps work.  I always thought a motto of containers was to "treat them like cattle" whereby the data and application were separate.  You could through away the container separate from the configuration and data.  In this implementation however this truly isn't the case.  Since the configuration is intermingled within the actual data it's really hard to "start over" with a fresh configuration because remnants of the old configuration are contained within the data.  Thank goodness for zfs snapshots on my end, however it's just really difficult to work with.  I'm honestly learning a lot more about openldap than I really cared to know, but it's very confusing since there isn't great documentation on where this project is storing it's modifications.  Perhaps if I spun up a VM with with openldap/slapd I would likely understand a lot better, however in doing so this in some ways defeats the abstraction layer containers are supposed to present. 

Thanks for your posts since with some of your suggestions I really would not have made it as far as I have.

**Comment by kevdogg** [comment]
@pcolmer 

I'm often running into the following error: 5ff76144 read_config: no serverID / URL match found. Check slapd -h arguments.

It seems the problem is with my /etc/hosts file the doesn't contain the 0.0.0.0 entry.  

With a non-working setup, my /etc/hosts file appears as:

```
# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.160.0.2	openldap2.domain.com openldap2
10.90.0.4	openldap2.domain.com openldap2
```

Whereas for a working container, it will appear as the following:

```
# cat /etc/hosts
0.0.0.0 openldap.domain.com openldap
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```

On both sets of containers (working and non-working):

(Non-working)
# hostname
openldap2
# hostname --fqdn
openldap2.domain.com

(Working)
# hostname
openldap
# hostname --fqdn
openldap.domain.com

I've noticed the 0.0.0.0 entry is added at the very end of the /container/service/slapd/startup.sh file the following:

```
FQDN="$(/bin/hostname --fqdn)"
if [ "$FQDN" != "$HOSTNAME" ]; then
    FQDN_PARAM="$FQDN"
else
    FQDN_PARAM=""
fi
ETC_HOSTS=$(cat /etc/hosts | sed "/$HOSTNAME/d")
echo "0.0.0.0 $FQDN_PARAM $HOSTNAME" > /etc/hosts
echo "$ETC_HOSTS" >> /etc/hosts
```

So it would appear this startup.sh file should be executed everytime as there is really no conditional for not writing the 0.0.0.0 parameter.

Why in some cases as demonstrated above is this line not added to the /etc/hosts file?

**Comment by pcolmer** [comment]
> So it would appear this startup.sh file should be executed everytime as there is really no conditional for not writing the 0.0.0.0 parameter.

To be honest, I think that this needs to be raised as a separate GitHub issue as it is more to do with how the Docker image is initialised than specifically LDAP itself.

**Comment by pcolmer** [comment]
I appreciate that a lot of people have been using this GitHub issue as a common contact point for getting help with their LDAP replication problems, and I'm happy to help when I can, but it is becoming a little bit unwieldy handling conversations this way.

Since the original problems I documented in this issue have been dealt with by the incorporation of https://github.com/osixia/docker-openldap/pull/420, I'm going to close this comment.

If anyone is having LDAP replication issues with the latest Docker container, I suggest you create a new GitHub issue and, if you want, tag me in your comment. I can't guarantee that I can help but I will do my best 😉
