### ISSUE TITLE
Unable to start container with the following invocation.

### ISSUE THREAD

**Issue by chamunks** [osixia/docker-openldap#6]
docker run --name container-ldap -p 389:389 -p 636:636 -e LDAP_ORGANISATION=ORG -e LDAP_DOMAIN=ldap.REDACTED -e LDAP_ADMIN_PASSWORD=REDACTED -v /root/docker-ldap/database:/var/lib/ldap -v /root/docker-ldap/config:/etc/ldap/slapd.d -d osixia/openldap

    root@ubuntu:~/docker-ldap# docker logs nixius-ldap
    *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
    *** Running /etc/my_init.d/slapd...
    *** /etc/my_init.d/slapd failed with status 1
    
    *** Killing all processes...
    *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
    *** Running /etc/my_init.d/slapd...
    *** /etc/my_init.d/slapd failed with status 1
    
    *** Killing all processes...

**Comment by osixia** [comment]
The first execution of this command seems ok,
But i have the same error on the second run.

This is probably due to missing TLS certificate files. On the first run by default the container initialise slapd to use TLS, and create a default certificate/key in /osixia/slapd/ssl. 
On the second run these files are not available and slapd config failed during the container start.

Quick fix, add volume with TLS files :
docker run --name container-ldap -p 389:389 -p 636:636 -e LDAP_ORGANISATION=ORG -e LDAP_DOMAIN=ldap.REDACTED -e LDAP_ADMIN_PASSWORD=REDACTED -v /root/docker-ldap/database:/var/lib/ldap -v /root/docker-ldap/config:/etc/ldap/slapd.d -v /root/docker-ldap/ssl:/osixia/slapd/ssl -d osixia/openldap

I'm working on a better solution,
thanks for reporting this bug
